### ISSUE TITLE
Funcionamiento incorrecto en horizontal

### ISSUE THREAD

**Issue by robertoccu** [UNIZAR-30226-2018-05/Android#2]
La reproducción funciona incorrectamente al cambiar la orientación. Revisar savedInstanceState, puede servir para arreglarlo.

Commit 65077f3

**Comment by pepelongares** [comment]
Arreglada la seekBar, trabajando en los campos de tiempo

**Comment by robertoccu** [comment]
Arreglado por completo en el Commit 038b446
